FROM node:22-alpine AS builder

ENV NODE_ENV production

WORKDIR /app/frontend

COPY package.json yarn.lock ./

RUN yarn install --production
RUN vite build

FROM nginx:alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]