# Generated by Django 5.0a1 on 2024-05-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="cv.logo",
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
        migrations.AddField(
            model_name="publisher",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publishers",
                to="cv.logo",
                verbose_name="Logo",
            ),
        ),
    ]
