# Generated by Django 5.0a1 on 2024-05-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_company_logo_company_website_publisher_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-date"],
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
        migrations.AlterModelOptions(
            name="collaborator",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Collaborator",
                "verbose_name_plural": "Collaborators",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "ordering": ["pk"],
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Infos",
            },
        ),
        migrations.AlterModelOptions(
            name="contactway",
            options={
                "ordering": ["title"],
                "verbose_name": "Contact Way",
                "verbose_name_plural": "Contact Ways",
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-education_range"],
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.AlterModelOptions(
            name="honor",
            options={
                "ordering": ["-date"],
                "verbose_name": "Honor",
                "verbose_name_plural": "Honors",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ["name"],
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterModelOptions(
            name="logo",
            options={
                "ordering": ["pk"],
                "verbose_name": "Logo",
                "verbose_name_plural": "Logos",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["name"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.AlterModelOptions(
            name="presentation",
            options={
                "ordering": ["-date"],
                "verbose_name": "Presentation",
                "verbose_name_plural": "Presentations",
            },
        ),
        migrations.AlterModelOptions(
            name="presentationdocument",
            options={
                "ordering": ["pk"],
                "verbose_name": "Presentation Document",
                "verbose_name_plural": "Presentation Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="presentationtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Presentation Type",
                "verbose_name_plural": "Presentation Types",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-project_range"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectproperty",
            options={
                "ordering": ["key"],
                "verbose_name": "Project Property",
                "verbose_name_plural": "Project Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="projectpropertyvalue",
            options={
                "ordering": ["pk"],
                "verbose_name": "Project Property Value",
                "verbose_name_plural": "Project Property Values",
            },
        ),
        migrations.AlterModelOptions(
            name="projecttype",
            options={
                "ordering": ["name"],
                "verbose_name": "Project Type",
                "verbose_name_plural": "Project Types",
            },
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={
                "ordering": ["name"],
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
            },
        ),
        migrations.AlterModelOptions(
            name="researchdocument",
            options={
                "ordering": ["pk"],
                "verbose_name": "Research Document",
                "verbose_name_plural": "Research Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="researchexperience",
            options={
                "ordering": ["-date"],
                "verbose_name": "Research Experience",
                "verbose_name_plural": "Research Experiences",
            },
        ),
        migrations.AlterModelOptions(
            name="researchtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Research Type",
                "verbose_name_plural": "Research Types",
            },
        ),
        migrations.AlterModelOptions(
            name="setting",
            options={
                "ordering": ["key"],
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="settingkey",
            options={
                "ordering": ["key"],
                "verbose_name": "Setting Key",
                "verbose_name_plural": "Setting Keys",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={
                "ordering": ["-cooperation_range"],
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
            },
        ),
    ]
