# Generated by Django 5.0a1 on 2024-05-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_alter_certificate_options_alter_collaborator_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="certificates",
                to="cv.skill",
                verbose_name="Skills",
            ),
        ),
        migrations.AddField(
            model_name="honor",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="honors", to="cv.skill", verbose_name="Skills"
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="presentations",
                to="cv.skill",
                verbose_name="Skills",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="cv.skill",
                verbose_name="Skills",
            ),
        ),
        migrations.AddField(
            model_name="researchexperience",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="research_experiences",
                to="cv.skill",
                verbose_name="Skills",
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="work_experiences",
                to="cv.skill",
                verbose_name="Skills",
            ),
        ),
    ]
