# Generated by Django 5.0a1 on 2024-05-24 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_certificate_skills_honor_skills_presentation_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FileField(
                        upload_to="settings/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    ".jpeg",
                                    ".jpg",
                                    ".png",
                                    ".svg",
                                    ".pdf",
                                    ".txt",
                                    ".doc",
                                    ".docx",
                                    ".xls",
                                    ".xlsx",
                                    ".ppt",
                                    ".pptx",
                                )
                            )
                        ],
                        verbose_name="Value",
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cv.settingkey",
                        verbose_name="Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ["key"],
            },
        ),
    ]
