/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LostBoyz2078 (https://sketchfab.com/LostModels2025)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/crow-fly-f47a1a1729544846a2bce22cc6adb500
Title: Crow Fly
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_10: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    M_CrowWings: THREE.MeshStandardMaterial
    M_CrowBody: THREE.MeshStandardMaterial
  }
}

// type ActionName = 'GltfAnimation 0'
// eslint-disable-next-line @typescript-eslint/no-var-requires
const crowScene = require("../assets/3d/crow/scene.gltf")

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(crowScene) as GLTFResult
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="GLTF_created_0">
                <primitive object={nodes.GLTF_created_0_rootJoint} />
                <skinnedMesh
                  name="Object_7"
                  geometry={nodes.Object_7.geometry}
                  material={materials.M_CrowWings}
                  skeleton={nodes.Object_7.skeleton}
                />
                <skinnedMesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.M_CrowBody}
                  skeleton={nodes.Object_10.skeleton}
                />
                <group name="0000_SK_Crow_43">
                  <group name="0000_SK_Crow_44" />
                </group>
                <group name="0001_SK_Crow_45">
                  <group name="0001_SK_Crow_46" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(crowScene)
