/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ПГГПУ (https://sketchfab.com/vrpspu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ornhusker-497b8e54761f418495222bfb74effb91
Title: Сornhusker
*/

import * as THREE from 'three';
import { SetStateAction, useEffect, useRef } from 'react';
import { useAnimations, useGLTF } from '@react-three/drei';
import { Dispatch } from 'react';
import PlaneScene from '../assets/3d/plane/scene.glb';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['Line003_Material_#398_0']: THREE.Mesh;
    ['Line003_Material_#380_0']: THREE.Mesh;
    ['Line003_Material_#290_0']: THREE.Mesh;
    ['Line003_Material_#347_0']: THREE.Mesh;
    ['Line003_Material_#115_0']: THREE.Mesh;
    ['Line003_Material_#261_0']: THREE.Mesh;
    ['Line003_Material_#185_0']: THREE.Mesh;
    ['Line003_Material_#150_0']: THREE.Mesh;
    ['Line003_Material_#198_0']: THREE.Mesh;
    ['Line003_Material_#102_0']: THREE.Mesh;
    ['Line003_Material_#363_0']: THREE.Mesh;
    ['Cylinder002_Material_#579_0']: THREE.Mesh;
    ['Object002_Material_#579_0']: THREE.Mesh;
    ['Box001_Material_#238_0']: THREE.Mesh;
    ['Box001_Material_#115_0']: THREE.Mesh;
    ['Object007_Material_#398_0']: THREE.Mesh;
    ['Object006_Material_#398_0']: THREE.Mesh;
    ['Object006_Material_#380_0']: THREE.Mesh;
    ['Object005_Material_#398_0']: THREE.Mesh;
    ['Object005_Material_#380_0']: THREE.Mesh;
    ['Object004_Material_#398_0']: THREE.Mesh;
    ['Object003_Material_#398_0']: THREE.Mesh;
  };
  materials: {
    Material_398: THREE.MeshPhysicalMaterial;
    Material_380: THREE.MeshPhysicalMaterial;
    Material_290: THREE.MeshPhysicalMaterial;
    Material_347: THREE.MeshPhysicalMaterial;
    Material_115: THREE.MeshPhysicalMaterial;
    Material_261: THREE.MeshPhysicalMaterial;
    Material_185: THREE.MeshPhysicalMaterial;
    Material_150: THREE.MeshPhysicalMaterial;
    Material_198: THREE.MeshPhysicalMaterial;
    Material_102: THREE.MeshPhysicalMaterial;
    Material_363: THREE.MeshPhysicalMaterial;
    Material_579: THREE.MeshPhysicalMaterial;
    Material_238: THREE.MeshPhysicalMaterial;
  };
};

type PlaneProps = JSX.IntrinsicElements['group'] & {
  isRotating: boolean;
};
type ActionName = '����';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Plane(props: PlaneProps) {
  const planeRef = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(PlaneScene) as GLTFResult;
  const { actions } = useAnimations(animations, planeRef);
  const { isRotating } = props;

  useEffect(() => {
    if (!actions['����']) return;

    if (isRotating) {
      actions['����'].play();
    } else {
      actions['����'].stop();
    }
  }, [isRotating, actions]);

  return (
    <group ref={planeRef} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={4.8652}
        >
          <group
            name="kukuruznikfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.0254}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Line003"
                  position={[-47.1194, 24.6417, -10.6784]}
                  rotation={[0, -1.5705, 0]}
                >
                  <group name="Object_5" position={[0.0151, -0.1823, -47.1194]}>
                    <mesh
                      name="Line003_Material_#398_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#398_0'].geometry}
                      material={materials.Material_398}
                    />
                    <mesh
                      name="Line003_Material_#380_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#380_0'].geometry}
                      material={materials.Material_380}
                    />
                    <mesh
                      name="Line003_Material_#290_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#290_0'].geometry}
                      material={materials.Material_290}
                    />
                    <mesh
                      name="Line003_Material_#347_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#347_0'].geometry}
                      material={materials.Material_347}
                    />
                    <mesh
                      name="Line003_Material_#115_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#115_0'].geometry}
                      material={materials.Material_115}
                    />
                    <mesh
                      name="Line003_Material_#261_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#261_0'].geometry}
                      material={materials.Material_261}
                    />
                    <mesh
                      name="Line003_Material_#185_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#185_0'].geometry}
                      material={materials.Material_185}
                    />
                    <mesh
                      name="Line003_Material_#150_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#150_0'].geometry}
                      material={materials.Material_150}
                    />
                    <mesh
                      name="Line003_Material_#198_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#198_0'].geometry}
                      material={materials.Material_198}
                    />
                    <mesh
                      name="Line003_Material_#102_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#102_0'].geometry}
                      material={materials.Material_102}
                    />
                    <mesh
                      name="Line003_Material_#363_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Line003_Material_#363_0'].geometry}
                      material={materials.Material_363}
                    />
                  </group>
                  <group
                    name="Cylinder002"
                    position={[34.1282, -7.7871, -28.1181]}
                    rotation={[Math.PI, 0, -Math.PI]}
                    scale={[1, 1, 0.5589]}
                  >
                    <mesh
                      name="Cylinder002_Material_#579_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Cylinder002_Material_#579_0'].geometry}
                      material={materials.Material_579}
                    />
                  </group>
                  <group
                    name="Object002"
                    position={[-6.7927, -15.4984, -28.5222]}
                  >
                    <group
                      name="Object_20"
                      position={[6.8078, 15.316, -18.5972]}
                    >
                      <mesh
                        name="Object002_Material_#579_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object002_Material_#579_0'].geometry}
                        material={materials.Material_579}
                      />
                    </group>
                  </group>
                  <group
                    name="Box001"
                    position={[-17.6796, -3.7222, -28.5318]}
                    rotation={[-0.0029, -1.5705, 0]}
                    scale={[1, 2.3537, 69.2526]}
                  >
                    <group
                      name="Object_23"
                      position={[-0.0193, -0.0143, -0.004]}
                    >
                      <mesh
                        name="Box001_Material_#238_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Box001_Material_#238_0'].geometry}
                        material={materials.Material_238}
                      />
                      <mesh
                        name="Box001_Material_#115_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Box001_Material_#115_0'].geometry}
                        material={materials.Material_115}
                      />
                    </group>
                  </group>
                  <group name="Object007" position={[33.028, 2.8995, -28.5539]}>
                    <group
                      name="Object_27"
                      position={[-33.0128, -3.0818, -18.5655]}
                    >
                      <mesh
                        name="Object007_Material_#398_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object007_Material_#398_0'].geometry}
                        material={materials.Material_398}
                      />
                    </group>
                  </group>
                  <group
                    name="Object006"
                    position={[32.4955, 0.7855, -20.1636]}
                    rotation={[0, -Math.PI / 2, 0]}
                  >
                    <group
                      name="Object_30"
                      position={[-26.9558, -0.9678, 32.4804]}
                      rotation={[0, Math.PI / 2, 0]}
                    >
                      <mesh
                        name="Object006_Material_#398_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object006_Material_#398_0'].geometry}
                        material={materials.Material_398}
                      />
                      <mesh
                        name="Object006_Material_#380_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object006_Material_#380_0'].geometry}
                        material={materials.Material_380}
                      />
                    </group>
                  </group>
                  <group
                    name="Object005"
                    position={[32.4955, 0.7855, -36.9333]}
                    rotation={[0, -Math.PI / 2, 0]}
                  >
                    <group
                      name="Object_34"
                      position={[-10.1861, -0.9678, 32.4804]}
                      rotation={[0, Math.PI / 2, 0]}
                    >
                      <mesh
                        name="Object005_Material_#398_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object005_Material_#398_0'].geometry}
                        material={materials.Material_398}
                      />
                      <mesh
                        name="Object005_Material_#380_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object005_Material_#380_0'].geometry}
                        material={materials.Material_380}
                      />
                    </group>
                  </group>
                  <group
                    name="Object004"
                    position={[0.5044, 6.2411, 0.0408]}
                    rotation={[-3.1415, -1.5621, -3.0786]}
                  >
                    <group
                      name="Object_38"
                      position={[-47.4644, -3.4503, 0.9008]}
                      rotation={[1.709, 1.5074, -1.7088]}
                    >
                      <mesh
                        name="Object004_Material_#398_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object004_Material_#398_0'].geometry}
                        material={materials.Material_398}
                      />
                    </group>
                  </group>
                  <group
                    name="Object003"
                    position={[0.4772, 6.2411, -57.2064]}
                    rotation={[0.0873, Math.PI / 2, 0]}
                  >
                    <group
                      name="Object_41"
                      position={[-10.6084, -5.5198, -0.4621]}
                      rotation={[-Math.PI / 2, -1.4835, -Math.PI / 2]}
                    >
                      <mesh
                        name="Object003_Material_#398_0"
                        castShadow
                        receiveShadow
                        geometry={nodes['Object003_Material_#398_0'].geometry}
                        material={materials.Material_398}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(PlaneScene);
